import { createStore } from "zustand";

export type SalesState = {
    orders: Array<OrderState>;
}

export type SalesActions = {
    addOrder: (order: OrderModuleProps) => void;
    removeOrder: (id: string) => void;
    // updateOrderAttachments: (id: string, attachment?: File) => void;
    // updateOrderStatus: (id: string, updatedStatus: string) => void;
}

export type SalesStore = SalesState & SalesActions;

export const defaultInitState: SalesState = {
  orders: [
    {
      uuid: "1",
      status: "submitted",
      collaborator: "JohnDoe",
      platform: "Twitch",
      price: 50,
      comment: "Make it so engaging that it goes viral on the gaming community!",
      attachments: undefined,
    },
    {
      uuid: "2",
      status: "payment",
      collaborator: "JaneSmith",
      platform: "Instagram",
      price: 35,
      comment: "I want my story to be eye-catching with vibrant visuals!",
      attachments: undefined,
    },
    {
      uuid: "3",
      status: "canceled",
      collaborator: "CoolCat",
      platform: "TikTok",
      price: 25,
      comment: "Create a trendy challenge that gets everyone participating!",
      attachments: undefined,
    },
    {
      uuid: "4",
      status: "progress",
      collaborator: "TechGuru",
      platform: "YouTube",
      price: 100,
      comment: "Make an in-depth review that tech enthusiasts will love!",
      attachments: undefined,
    },
    {
      uuid: "5",
      status: "progress",
      collaborator: "FoodieFun",
      platform: "Pinterest",
      price: 40,
      comment: "I want a mouth-watering recipe post with step-by-step photos!",
      attachments: undefined,
    },
    {
      uuid: "6",
      status: "submitted",
      collaborator: "TravelBuddy",
      platform: "Facebook",
      price: 60,
      comment: "Capture the essence of wanderlust in a captivating travel video!",
      attachments: undefined,
    },
    {
      uuid: "7",
      status: "progress",
      collaborator: "FitnessFreak",
      platform: "Instagram",
      price: 55,
      comment: "Create a motivational post that inspires my followers to workout!",
      attachments: undefined,
    },
    {
      uuid: "8",
      status: "canceled",
      collaborator: "GadgetGuy",
      platform: "YouTube",
      price: 80,
      comment: "Unbox and review the latest gadgets with a fun twist!",
      attachments: undefined,
    },
    {
      uuid: "9",
      status: "canceled",
      collaborator: "BeautyQueen",
      platform: "TikTok",
      price: 45,
      comment: "Showcase a makeup tutorial that's both glamorous and easy to follow!",
      attachments: undefined,
    },
    {
      uuid: "10",
      status: "progress",
      collaborator: "EcoWarrior",
      platform: "Twitter",
      price: 30,
      comment: "Promote eco-friendly tips in a concise and impactful thread!",
      attachments: undefined,
    },
    {
      uuid: "11",
      status: "submitted",
      collaborator: "ArtisticSoul",
      platform: "DeviantArt",
      price: 70,
      comment: "Create an artwork that reflects the beauty of nature!",
      attachments: undefined,
    },
    {
      uuid: "12",
      status: "payment",
      collaborator: "Fashionista",
      platform: "Instagram",
      price: 40,
      comment: "Showcase my latest fashion collection with stunning visuals!",
      attachments: undefined,
    },
    {
      uuid: "13",
      status: "canceled",
      collaborator: "GamerX",
      platform: "Twitch",
      price: 55,
      comment: "Create a live stream event that will attract a massive audience!",
      attachments: undefined,
    },
    {
      uuid: "14",
      status: "progress",
      collaborator: "TechNerd",
      platform: "YouTube",
      price: 90,
      comment: "Review the latest smartphone with in-depth analysis!",
      attachments: undefined,
    },
    {
      uuid: "15",
      status: "progress",
      collaborator: "CulinaryKing",
      platform: "Pinterest",
      price: 50,
      comment: "Share a recipe that's both delicious and easy to follow!",
      attachments: undefined,
    },
    {
      uuid: "16",
      status: "submitted",
      collaborator: "TravelGuru",
      platform: "YouTube",
      price: 85,
      comment: "Create a travel vlog that captures the essence of adventure!",
      attachments: undefined,
    },
    {
      uuid: "17",
      status: "progress",
      collaborator: "HealthNut",
      platform: "Instagram",
      price: 65,
      comment: "Post a guide on healthy living and fitness tips!",
      attachments: undefined,
    },
    {
      uuid: "18",
      status: "canceled",
      collaborator: "GadgetGeek",
      platform: "YouTube",
      price: 75,
      comment: "Unbox and review the latest tech gadgets with enthusiasm!",
      attachments: undefined,
    },
    {
      uuid: "19",
      status: "canceled",
      collaborator: "BeautyBlogger",
      platform: "YouTube",
      price: 60,
      comment: "Create a makeup tutorial that showcases bold and vibrant colors!",
      attachments: undefined,
    },
    {
      uuid: "20",
      status: "progress",
      collaborator: "EcoFriendly",
      platform: "Facebook",
      price: 45,
      comment: "Share tips on how to live a more sustainable and eco-friendly life!",
      attachments: undefined,
    },
    {
      uuid: "21",
      status: "submitted",
      collaborator: "MusicLover",
      platform: "SoundCloud",
      price: 50,
      comment: "Mix and master my latest track to perfection!",
      attachments: undefined,
    },
    {
      uuid: "22",
      status: "payment",
      collaborator: "AutoEnthusiast",
      platform: "YouTube",
      price: 85,
      comment: "Create a review video of the latest sports car!",
      attachments: undefined,
    },
    {
      uuid: "23",
      status: "canceled",
      collaborator: "MovieBuff",
      platform: "Letterboxd",
      price: 25,
      comment: "Write a detailed review of the latest blockbuster!",
      attachments: undefined,
    },
    {
      uuid: "24",
      status: "progress",
      collaborator: "PetLover",
      platform: "Instagram",
      price: 40,
      comment: "Share adorable pet photos with creative captions!",
      attachments: undefined,
    },
    {
      uuid: "25",
      status: "progress",
      collaborator: "GreenThumb",
      platform: "Pinterest",
      price: 35,
      comment: "Create a garden guide that's perfect for beginners!",
      attachments: undefined,
    },
    {
      uuid: "26",
      status: "submitted",
      collaborator: "FitnessFanatic",
      platform: "YouTube",
      price: 65,
      comment: "Record a workout routine that's challenging yet accessible!",
      attachments: undefined,
    },
    {
      uuid: "27",
      status: "progress",
      collaborator: "BookWorm",
      platform: "Goodreads",
      price: 20,
      comment: "Write a review of the latest best-seller!",
      attachments: undefined,
    },
    {
      uuid: "28",
      status: "canceled",
      collaborator: "ChefExtraordinaire",
      platform: "Instagram",
      price: 55,
      comment: "Post a recipe video with mouth-watering visuals!",
      attachments: undefined,
    },
    {
      uuid: "29",
      status: "canceled",
      collaborator: "TravelNomad",
      platform: "YouTube",
      price: 80,
      comment: "Create a travel guide that highlights hidden gems!",
      attachments: undefined,
    },
    {
      uuid: "30",
      status: "progress",
      collaborator: "ArtistAtHeart",
      platform: "DeviantArt",
      price: 60,
      comment: "Create an art piece that reflects the beauty of the human experience!",
      attachments: undefined,
    },
  ]
  ,
}

export const createSalesStore = (
    initState: SalesState = defaultInitState,
) => {
    return createStore<SalesStore>()((set)=> ({
        ...initState,
        addOrder(order) {
            set((state)=> ({...state, order}))
        },
        removeOrder(id) {
            set((state) => ({...state, orders: state.orders.filter(order => order.uuid !== id)}))
        },
    }))
}